name: manage_salary
description: A new Flutter manager salary application.
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  bloc: ^9.0.0 
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.5

  # UI Components
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.7
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  animated_notch_bottom_bar: ^1.0.3
  flutter_tilt: ^3.2.1
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^6.0.0

  # Navigation & Routing
  go_router: ^12.1.1

  # Utilities & Services
  intl: ^0.19.0
  intl_utils: ^2.8.10
  path_provider: ^2.1.5
  logger: ^2.0.2+1
  uuid: ^4.5.1

  # Network & Connectivity
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.1.3

  # Local Storage
  shared_preferences: ^2.5.3

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  flutter_lints: ^5.0.0
  build_runner: any
  json_serializable: ^6.6.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21

flutter_intl:
  enabled: true # Enables Flutter Intl
  class_name: S # Name of the generated localization class
  main_locale: en # Main locale for the application
  arb_dir: lib/core/locale/l10n # Directory for ARB resource files
  output_dir: lib/core/locale/generated # Directory for generated localization files

flutter_native_splash:
  color: "#80D0C7"
  image: assets/icons/launcher_icon.png
  branding: assets/icons/launcher_icon.png
  color_dark: "#121212"
  image_dark: assets/icons/launcher_icon.png
  branding_dark: assets/icons/launcher_icon.png

  android_12:
    image: assets/icons/launcher_icon.png
    icon_background_color: "#80D0C7"
    image_dark: assets/icons/launcher_icon.png
    icon_background_color_dark: "#121212"
