name: manage_salary
description: "A new Flutter manager salary application."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

# Dart SDK version constraints
environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies for the application
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  intl: ^0.19.0 # For internationalization and formatting
  intl_utils: ^2.8.10 # For generating localization files
  go_router: ^12.1.1 # For navigation and routing
  equatable: ^2.0.5 # For value equality in Dart objects
  json_annotation: ^4.8.1 # For JSON serialization
  bloc: ^8.1.2 # Core Bloc library for state management
  flutter_bloc: ^8.1.3 # Bloc integration with Flutter
  hydrated_bloc: ^9.1.2 # Persistent state management with Bloc
  flutter_screenutil: ^5.9.1 # For responsive UI design
  flutter_svg: ^2.0.7 # For rendering SVG images
  flutter_form_builder: ^10.0.1 # For building forms in Flutter
  form_builder_validators: ^11.1.2 # Validators for form fields
  get_it: ^7.6.4 # Dependency injection
  injectable: ^2.3.2 # Code generation for dependency injection
  cupertino_icons: ^1.0.8 # iOS-style icons
  logger: ^2.0.2+1
  # Network
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.1.3

  # Local storage
  shared_preferences: ^2.5.3


  animated_notch_bottom_bar: ^1.0.3
  flutter_tilt: ^3.2.1

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter # For testing Flutter applications
  injectable_generator: ^2.7.0 # Code generator for injectable
  flutter_lints: ^5.0.0 # Recommended lint rules for Flutter
  build_runner: any # For code generation
  json_serializable: ^6.6.0 # For generating JSON serialization code

# Flutter-specific configurations
flutter:
  uses-material-design: true # Enables Material Icons

  # Assets directory
  assets:

# Flutter Intl configuration for localization
flutter_intl:
  enabled: true # Enables Flutter Intl
  class_name: S # Name of the generated localization class
  main_locale: en # Main locale for the application
  arb_dir: lib/core/locale/l10n # Directory for ARB resource files
  output_dir: lib/core/locale/generated # Directory for generated localization files